# -*- coding: utf-8 -*-
"""text generation code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1snahjudwiO8pQu6t5TkZ9EBp9hENb5sK
"""

!pip install transformers torch

from transformers import pipeline
#Load text generation model (GenAI)
generator = pipeline(
    "text-generation",
    model="gpt2"
    )
#input code
prompt = "Artificial Intelligence in finance will"
#generate text
result=generator(prompt,max_length=50,num_return_sequences=1)

print("AI Generated Text")
print(result[0]['generated_text'])